-- begin TESIS_EMPLOYEE
alter table TESIS_EMPLOYEE add constraint FK_TESIS_EMPLOYEE_ON_CENTER foreign key (CENTER_ID) references TESIS_CAR_SERVICE_CENTER(ID)^
create index IDX_TESIS_EMPLOYEE_ON_CENTER on TESIS_EMPLOYEE (CENTER_ID)^
-- end TESIS_EMPLOYEE
-- begin TESIS_CAR_SERVICE_CENTER
alter table TESIS_CAR_SERVICE_CENTER add constraint FK_TESIS_CAR_SERVICE_CENTER_ON_CITY foreign key (CITY_ID) references TESIS_CITY(ID)^
create index IDX_TESIS_CAR_SERVICE_CENTER_ON_CITY on TESIS_CAR_SERVICE_CENTER (CITY_ID)^
-- end TESIS_CAR_SERVICE_CENTER
-- begin TESIS_REPAIR
alter table TESIS_REPAIR add constraint FK_TESIS_REPAIR_ON_CENTER foreign key (CENTER_ID) references TESIS_CAR_SERVICE_CENTER(ID)^
alter table TESIS_REPAIR add constraint FK_TESIS_REPAIR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references TESIS_EMPLOYEE(ID)^
create index IDX_TESIS_REPAIR_ON_CENTER on TESIS_REPAIR (CENTER_ID)^
create index IDX_TESIS_REPAIR_ON_EMPLOYEE on TESIS_REPAIR (EMPLOYEE_ID)^
-- end TESIS_REPAIR
-- begin TESIS_CAR_SERVICE_CENTER_CUSTOMER_LINK
alter table TESIS_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references TESIS_CAR_SERVICE_CENTER(ID)^
alter table TESIS_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CUSTOMER foreign key (CUSTOMER_ID) references TESIS_CUSTOMER(ID)^
-- end TESIS_CAR_SERVICE_CENTER_CUSTOMER_LINK
-- begin TESIS_CUSTOMER_INDIVIDUAL
alter table TESIS_CUSTOMER_INDIVIDUAL add constraint FK_TESIS_CUSTOMER_INDIVIDUAL_ON_CUSTOMER foreign key (customer_id) references TESIS_CUSTOMER(ID) on delete CASCADE^
-- end TESIS_CUSTOMER_INDIVIDUAL
-- begin TESIS_CUSTOMER_COMPANY
alter table TESIS_CUSTOMER_COMPANY add constraint FK_TESIS_CUSTOMER_COMPANY_ON_CUSTOMER foreign key (customer_id) references TESIS_CUSTOMER(ID) on delete CASCADE^
-- end TESIS_CUSTOMER_COMPANY
